### ISSUE TITLE
Is the type system decidable?

### ISSUE THREAD

**Issue by Hirrolot** [vekatze/neut#93]
The project README mentions that the type system of Neut is "roughly CoC + ADT + fix - universe hierarchy". A natural question to ask is whether Neut's type system is decidable? Since it's dependently typed, if we permit unbounded recursion and Girard's paradox, there's a danger that the type checker will loop forever.

I can't find anything in the documentation on this matter, so I think it'd be nice to include it somewhere.

**Comment by vekatze** [comment]
Since type inference in System F is undecidable, I think type inference in Neut (⊇ System F) is also undecidable.

As for infinite loop thing, if we construct a term `t` that loops forever without relying on top-level definitions or fix, I believe we can trigger an infinite loop in the current implementation of the checker by writing something like `define foo(x: t) {..}`. This is because the checker tries to reduce the term `t` when performing unification.

Perhaps I might want to limit the maximum number of reduction steps when performing elaboration in the implementation for better experience. Yes, some notes on undecidability might also be useful. Thanks for suggestion 🙏

**Comment by Hirrolot** [comment]
Thanks for your answer. I've just published my view on terminating evaluation for a dependently typed language like Neut: https://hirrolot.github.io/posts/fueled-evaluation.html.

The basic idea is to annotate every term with an mutable integer called _fuel_. Every time a term is fed into `eval`, decrement the fuel; if it is zero, raise an exception. I don't know how it'd look like in Haskell (esp. mutation -- but maybe `IORef` would suffice), but it's pretty straightforwardly expressible in OCaml.

This way, termination checking can be done in an easy and flexible manner. You may find more information in the above link.

Anyhow, thanks for the reply and I wish you all the best.
